package com.feibot.handsetforcheckuhf.utils

enum class CaseState {
    LOADING,
    SUCCESS,
    ERROR,
    NO_CHECK,
    EMPTY,
    NONE,
    DOWNLOAD_PLAYER_INFO_LOADING,
    DOWNLOAD_PLAYER_INFO_SUCCESS,
    DOWNLOAD_PLAYER_INFO_ERROR,
    DOWNLOAD_PLAYER_INFO_EMPTY,
    UPGRADE_LOADING,
    UPGRADE_SUCCESS,
    UPGRADE_UPGRADING,
    UPGRADE_INSTALLING,
    UPLOAD_LOADING,
    UPLOAD_SUCCESS,
    UPLOAD_ERROR,
    UPLOAD_FAIL,
    MAIN_READER_ON,
    REGISTERING,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    NEED_REGISTER,
    QUERY_HISTORY,
    ON_QUERY_HISTORY_LOADED
}

